ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 40, in main
    welcome = oWel.WelcomeWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\module\winwelcome.py", line 55, in __init__
    if not self.initWindow(warn="mode"):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\module\winwelcome.py", line 95, in initWindow
    self.brwsloc.insert(0, self.localdata["datafolderloca"])
KeyError: 'datafolderloca'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 40, in main
    welcome = oWel.WelcomeWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowwelcome.py", line 41, in __init__
    super(WelcomeWindow, self).__init__("Welcome to OpenMark!", self.localconfig, self.repoconfig, menu=False)
AttributeError: 'WelcomeWindow' object has no attribute 'localconfig'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 40, in main
    welcome = oWel.WelcomeWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowwelcome.py", line 41, in __init__
    super(WelcomeWindow, self).__init__("Welcome to OpenMark!", self.localconfig, self.repoconfig, menu=False)
AttributeError: 'WelcomeWindow' object has no attribute 'localconfig'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 40, in main
    welcome = oWel.WelcomeWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowwelcome.py", line 63, in __init__
    if not self.initWindow(warn="datafolderloca"):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowwelcome.py", line 70, in initWindow
    self.window.resizable(0,0) #block resizing for the welcome window.
  File "C:\Python34\lib\tkinter\__init__.py", line 1798, in wm_resizable
    return self.tk.call('wm', 'resizable', self._w, width, height)
_tkinter.TclError: can't invoke "wm" command: application has been destroyed
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localdata, welcome.repoconfig)
AttributeError: 'WelcomeWindow' object has no attribute 'localdata'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowadmin.py", line 29, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 40, in _initWindow
    self.window.attributes('-zoomed', True)
  File "C:\Python34\lib\tkinter\__init__.py", line 1616, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: wrong # args: should be "wm attributes window ?-alpha ?double?? ?-transparentcolor ?color?? ?-disabled ?bool?? ?-fullscreen ?bool?? ?-toolwindow ?bool?? ?-topmost ?bool??"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowadmin.py", line 29, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 41, in _initWindow
    self._centreWindow(self.window)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 54, in _centreWindow
    size(scx, scy)
TypeError: 'bool' object is not callable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowadmin.py", line 29, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 41, in _initWindow
    self._centreWindow(self.window)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 50, in _centreWindow
    menu_height = win.winfo_height() + (titlebar_height + frm_width)
NameError: name 'win' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowadmin.py", line 29, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 41, in _initWindow
    self._positionWindow(self.window)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 55, in _positionWindow
    size = (w-scx, h-scy-menu_height)
NameError: name 'menu_height' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    print(self.window.master())
TypeError: 'NoneType' object is not callable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    print(self.window.master())
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    print(self.window.master())
TypeError: 'NoneType' object is not callable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    self.window.master.quit()
AttributeError: 'NoneType' object has no attribute 'quit'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    self.window.master.quit()
AttributeError: 'NoneType' object has no attribute 'quit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    self.window.master.quit()
AttributeError: 'NoneType' object has no attribute 'quit'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 63, in _windowClose
    self.parentWindow.destroy()
AttributeError: 'MainWin' object has no attribute 'destroy'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 48, in _buildToolbar
    mainPane = tk.Frame(toolbarcontent, relief=tk.GROOVE, pdx=2, pady=2)
  File "C:\Python34\lib\tkinter\__init__.py", line 2582, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-pdx"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self.window.pack(fill=tk.X)
  File "C:\Python34\lib\tkinter\__init__.py", line 1932, in __getattr__
    return getattr(self.tk, attr)
AttributeError: 'tkapp' object has no attribute 'pack'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _buildToolbar
    mainPane = ttk.Frame(toolbarcontent, relief=tk.SUNKEN, padx=2, pady=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 736, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-pady"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    bottomSep = ttk.Separator(window, orient=tk.VERTICAL)
NameError: name 'window' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    mainPane.grid(row=0, col=1, sticky=tk.LEFT)
  File "C:\Python34\lib\tkinter\__init__.py", line 2057, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: ambiguous option "-col": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    mainPane.grid(row=0, col=0, sticky=tk.W)
  File "C:\Python34\lib\tkinter\__init__.py", line 2057, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: ambiguous option "-col": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    mainPane.grid(row=0, col=0, sticky=tk.W)
  File "C:\Python34\lib\tkinter\__init__.py", line 2057, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: ambiguous option "-col": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    mainPane.grid(row=0, col=0, sticky=(tk.W))
  File "C:\Python34\lib\tkinter\__init__.py", line 2057, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: ambiguous option "-col": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    toolbarcontent.pack(fill=tk.X)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside . which already has slaves managed by grid
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    modeSep = ttk.Separator(modepane, orient=tk.VERTICAL)
NameError: name 'modepane' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 70, in _buildToolbar
    modeSep.pack(side=tk.RIGHT, fill=tk.Y)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside .45659888.45659920 which already has slaves managed by grid
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state("pressed")
  File "C:\Python34\lib\tkinter\ttk.py", line 589, in state
    return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))
_tkinter.TclError: Invalid state name p
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 85, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", callback=self._windowClose)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-callback"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 75, in _windowClose
    self._windowPreClose()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 105, in _windowPreClose
    print(peopleButton.state())
NameError: name 'peopleButton' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 75, in _windowClose
    self._windowPreClose()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 105, in _windowPreClose
    print(peopleButton.state())
NameError: name 'peopleButton' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 48, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 86, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state("active")
  File "C:\Python34\lib\tkinter\ttk.py", line 589, in state
    return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))
_tkinter.TclError: Invalid state name a
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state("pressed")
  File "C:\Python34\lib\tkinter\ttk.py", line 589, in state
    return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))
_tkinter.TclError: Invalid state name p
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state('pressed')
  File "C:\Python34\lib\tkinter\ttk.py", line 589, in state
    return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))
_tkinter.TclError: Invalid state name p
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state(['pressed']['disabled'])
TypeError: list indices must be integers, not str
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 83, in _buildToolbar
    saveimg = tk.PhotoImage(file="resources/icons/save.gif")
  File "C:\Python34\lib\tkinter\__init__.py", line 3416, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 3372, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "resources/icons/save.gif": no such file or directory
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 71, in _BuildMainWindow
    mainNotebook.pack(fill=tk.BOTH)
NameError: name 'mainNotebook' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 72, in _BuildMainWindow
    rightNotebook1.add(rightNotebook1, text="Basic")
AttributeError: 'Frame' object has no attribute 'add'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 77, in _BuildMainWindow
    leftNotebook.pack(row=0, column=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-row": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(i, *testlist[i])
TypeError: list indices must be integers, not str
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(testlist[i])
TypeError: list indices must be integers, not str
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(testlist)
  File "C:\Python34\lib\tkinter\__init__.py", line 2644, in insert
    self.tk.call((self._w, 'insert', index) + elements)
_tkinter.TclError: bad listbox index "['Muresan, Matthew', 'Muresan, Tiffany']": must be active, anchor, end, @x,y, or a number
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(END, i, *testlist[i])
NameError: name 'END' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(tk.END, i, *testlist[i])
TypeError: list indices must be integers, not str
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 72, in _BuildMainWindow
    testlab = ttk.Label(basicInfo, text="test", relief=tk.GROOVE, background="#FFE6E6", width=20, height=1)
  File "C:\Python34\lib\tkinter\ttk.py", line 755, in __init__
    Widget.__init__(self, master, "ttk::label", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-height"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 80, in _BuildMainWindow
    testent.pack(row=0, column=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-row": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _BuildMainWindow
    testlab2.pack(row=0, column=3)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-row": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _BuildMainWindow
    basicInfo.colormodel(2, minsize=20)
TypeError: colormodel() got an unexpected keyword argument 'minsize'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 73, in _BuildMainWindow
    testlab = tk.Label(basicInfo, text="test", relief=tk.GROOVE, background="#FFE6E6", width=20, borderwidth=1, anchor=tk.RIGHT)
  File "C:\Python34\lib\tkinter\__init__.py", line 2604, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: bad anchor "right": must be n, ne, e, se, s, sw, w, nw, or center
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 74, in _BuildMainWindow
    testent = tk.Entry(basicInfo, relief=tk.GROOVE, background="#FFE6E6", activebackground="#FFF0F0", width=20, borderwidth=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 2514, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-activebackground"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 114, in _buildToolbar
    saveimg = tk.PhotoImage(file="resources\icons\bitcons\icons\gif\tan\16x16")
  File "C:\Python34\lib\tkinter\__init__.py", line 3416, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 3372, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "resources\iconsitcons\icons\gif	anx16": no such file or directory
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 114, in _buildToolbar
    saveimg = tk.PhotoImage(file="resources\icons\bitcons\icons\gif\tan\16x16\save.gif")
  File "C:\Python34\lib\tkinter\__init__.py", line 3416, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 3372, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "resources\iconsitcons\icons\gif	anx16\save.gif": no such file or directory
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 30, in __init__
    super(MainWin, self).__init__("OpenMarkAdmin", localconfig, repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 26, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 46, in _skelInit
    self.helpMenu.add_command(label="About", command=self._showAbout())
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramWindow()
NameError: name 'AboutProgramWindow' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 30, in __init__
    super(MainWin, self).__init__("OpenMarkAdmin", localconfig, repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 26, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 46, in _skelInit
    self.helpMenu.add_command(label="About", command=self._showAbout())
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 37, in _initWindow
    super(AboutProgramDialog, self).__init__("Welcome to OpenMark!", self.localconfig, self.repoconfig, menu=False)
AttributeError: 'AboutProgramDialog' object has no attribute 'localconfig'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 30, in __init__
    super(MainWin, self).__init__("OpenMarkAdmin", localconfig, repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 26, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 46, in _skelInit
    self.helpMenu.add_command(label="About", command=self._showAbout())
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 37, in _initWindow
    super(AboutProgramDialog, self).__init__("About OpenMarkSheets")
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialog.py", line 35, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialog.py", line 42, in _skelInit
    self.window = tk.Toplevel(self)
  File "C:\Python34\lib\tkinter\__init__.py", line 2165, in __init__
    BaseWidget.__init__(self, master, 'toplevel', cnf, {}, extra)
  File "C:\Python34\lib\tkinter\__init__.py", line 2115, in __init__
    BaseWidget._setup(self, master, cnf)
  File "C:\Python34\lib\tkinter\__init__.py", line 2093, in _setup
    self.tk = master.tk
AttributeError: 'AboutProgramDialog' object has no attribute 'tk'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 30, in __init__
    super(MainWin, self).__init__("OpenMarkAdmin", localconfig, repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 26, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 46, in _skelInit
    self.helpMenu.add_command(label="About", command=self._showAbout())
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 96, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 96, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 96, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 97, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 97, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit(0)
SystemExit: 0
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    os._exit()
TypeError: _exit() takes exactly 1 argument (0 given)
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    os._exit()
TypeError: _exit() takes exactly 1 argument (0 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    os._exit()
TypeError: _exit() takes exactly 1 argument (0 given)
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 62, in _initWindow
    ok = ttk.Button(buttonscontent, text="Okay", command=self._windowClose())
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: bad window path name ".45698448.45698576.45752464"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 51, in _BuildMainWindow
    leftNoteFrame = ttkFrame(mainwindow)
NameError: name 'ttkFrame' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 105, in _BuildMainWindow
    searchEnt.pack(side=tk.X, expand=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad side "x": must be top, bottom, left, or right
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 111, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData)
TypeError: _buildEntryTable() missing 1 required positional argument: 'vals'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 37, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 48, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 116, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 139, in _buildEntryTable
    ent1 = ttk.Entry(frame, style='OpenMark.TEntry', width=20, borderwidth=1)
  File "C:\Python34\lib\tkinter\ttk.py", line 665, in __init__
    Widget.__init__(self, master, widget or "ttk::entry", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 111, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 144, in _buildEntryTable
    lab2 = tk.Label(frame, text=tableData['labels'][i+1], relief=tk.GROOVE, background="#FFD9D9", width=20, borderwidth=1)
IndexError: list index out of range
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 107, in _BuildMainWindow
    tableData['basic']['text'][0]['labels'] = ["First Name"]
KeyError: 'basic'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 107, in _BuildMainWindow
    tableData['basic']['text'][0]['labels'] = ["First Name"]
KeyError: 'basic'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 107, in _BuildMainWindow
    tableData['basic']['text'][0]['name'] = "First Name"
KeyError: 'basic'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 119, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 142, in _buildEntryTable
    lab1 = tk.Label(frame, text=tableData['text'][i]['labels'], relief=tk.GROOVE, background="#FFD9D9", width=20, borderwidth=1)
KeyError: 'labels'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 182, in _saveDataTest
    print(json.dumps(self.JSONdata, sort_keys=True, indent=4, separators=(',', ': ')))
NameError: name 'json' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 33, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 44, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 96, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 120, in _buildEntryTable
    ent1 = tk.Entry(frame, textvariable=tableData['basic']['text'][0]['value'], relief=tk.GROOVE, background="#FFEBEB", width=20, borderwidth=1)
KeyError: 'basic'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 188, in _saveDataTest
    print(json.dumps(self.JSONdata, sort_keys=True, indent=1, separators=(',', ': ')))
  File "C:\Python34\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python34\lib\json\encoder.py", line 194, in encode
    chunks = list(chunks)
  File "C:\Python34\lib\json\encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 429, in _iterencode
    o = _default(o)
  File "C:\Python34\lib\json\encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <class 'tkinter.StringVar'> is not JSON serializable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 190, in _saveDataTest
    i['value'] = i['value'].get()
TypeError: get() missing 1 required positional argument: 'self'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 191, in _saveDataTest
    i['value'] = i['value'].get()
TypeError: get() missing 1 required positional argument: 'self'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 191, in _saveDataTest
    i['value'] = i['value'].get()
TypeError: get() missing 1 required positional argument: 'self'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 190, in _saveDataTest
    print(i['value'].get())
TypeError: get() missing 1 required positional argument: 'self'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 190, in _saveDataTest
    print(i['value'].get(self))
  File "C:\Python34\lib\tkinter\__init__.py", line 336, in get
    value = self._tk.globalgetvar(self._name)
AttributeError: 'MainWin' object has no attribute '_tk'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 190, in _saveDataTest
    print(i['value'].get(self.window))
  File "C:\Python34\lib\tkinter\__init__.py", line 336, in get
    value = self._tk.globalgetvar(self._name)
  File "C:\Python34\lib\tkinter\__init__.py", line 1932, in __getattr__
    return getattr(self.tk, attr)
AttributeError: 'tkapp' object has no attribute '_tk'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 191, in _saveDataTest
    i['value'] = i['value'].get()
TypeError: get() missing 1 required positional argument: 'self'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 33, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 44, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 96, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 124, in _buildEntryTable
    print(tableData['text'][i]['value'].get())
TypeError: get() missing 1 required positional argument: 'self'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 193, in _saveDataTest
    print(json.dumps(self.JSONdata, sort_keys=False, indent=1, separators=(',', ': ')))
  File "C:\Python34\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python34\lib\json\encoder.py", line 194, in encode
    chunks = list(chunks)
  File "C:\Python34\lib\json\encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 429, in _iterencode
    o = _default(o)
  File "C:\Python34\lib\json\encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tkinter.StringVar object at 0x02C16F30> is not JSON serializable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 33, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 44, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 95, in _BuildMainWindow
    tableData['basic']['phone'][3] = {}
KeyError: 'phone'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 33, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 44, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 97, in _BuildMainWindow
    tableData['basic']['phone'][0] = {}
IndexError: list assignment index out of range
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 144, in _validatePhoneNumber
    number = value.get()
AttributeError: 'str' object has no attribute 'get'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 102, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 131, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'phone', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 157, in _buildEntryTableSubEntry
    print(ent.validate)
AttributeError: 'Entry' object has no attribute 'validate'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 164, in <lambda>
    , validate='focusout', validatecommand=lambda:self._validatePhoneNumber(ent))
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 154, in _validatePhoneNumber
    entry.set(formattedNumber)
AttributeError: 'Entry' object has no attribute 'set'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 164, in <lambda>
    , validate='focusout', validatecommand=lambda:self._validatePhoneNumber(ent))
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 154, in _validatePhoneNumber
    entry.set(formattedNumber)
AttributeError: 'Entry' object has no attribute 'set'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 180, in <lambda>
    , validate='focusout', validatecommand=lambda:self._validatePhoneNumber(ent))
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 147, in _validatePhoneNumber
    if len(number == 7):
TypeError: object of type 'bool' has no len()
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 108, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 133, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'text', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 161, in _buildEntryTableSubEntry
    elif itemtype == 'list':
NameError: name 'itemtype' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 108, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 141, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 162, in _buildEntryTableSubEntry
    ent = tk.OptionMenu(frame, item['values'], relief=tk.GROOVE, background="#FFEBEB", width=20, borderwidth=1)
KeyError: 'values'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 108, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 141, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 162, in _buildEntryTableSubEntry
    ent = tk.OptionMenu(frame, item['values'], relief=tk.GROOVE, background="#FFEBEB", width=20, borderwidth=1)
TypeError: __init__() missing 1 required positional argument: 'value'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 108, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 141, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 164, in _buildEntryTableSubEntry
    ent = tk.OptionMenu(frame, var, item['values'], relief=tk.GROOVE, background="#FFEBEB", width=20, borderwidth=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 3331, in __init__
    raise TclError('unknown option -'+kwargs.keys()[0])
TypeError: 'dict_keys' object does not support indexing
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 108, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 141, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 168, in _buildEntryTableSubEntry
    ent.insert(0, enttext)
AttributeError: 'OptionMenu' object has no attribute 'insert'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 108, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 141, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 168, in _buildEntryTableSubEntry
    ent.insert(0, enttext)
AttributeError: 'OptionMenu' object has no attribute 'insert'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 108, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 141, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 165, in _buildEntryTableSubEntry
    ent = tk.OptionMenu(frame, var, item['values'], relief=tk.GROOVE, background="#FFEBEB", width=20, borderwidth=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 3331, in __init__
    raise TclError('unknown option -'+kwargs.keys()[0])
TypeError: 'dict_keys' object does not support indexing
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 108, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 141, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 166, in _buildEntryTableSubEntry
    ent.configure(relief=tk.GROOVE, background="#FFEBEB", width=20, borderwidth=1, height=1, ipady=0)
  File "C:\Python34\lib\tkinter\__init__.py", line 1319, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 1310, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-ipady"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 116, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 149, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 181, in _buildEntryTableSubEntry
    ent.grid(row=gridIndex['r'], column=gridIndex['c'], sticky=(tk.E, tk.W))
UnboundLocalError: local variable 'ent' referenced before assignment
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 116, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 149, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 174, in _buildEntryTableSubEntry
    ent.configure(relief=tk.GROOVE, background="#FFEBEB", width=20, borderwidth=1, activeborderwidth=0, pady=1, padx=0)
  File "C:\Python34\lib\tkinter\__init__.py", line 1319, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 1310, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-activeborderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 123, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 156, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 180, in _buildEntryTableSubEntry
    var.set(item['value'])
TypeError: set() missing 1 required positional argument: 'value'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 239, in _saveDataTest
    print(json.dumps(self.JSONdata, sort_keys=False, indent=1, separators=(',', ': ')))
  File "C:\Python34\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python34\lib\json\encoder.py", line 194, in encode
    chunks = list(chunks)
  File "C:\Python34\lib\json\encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 429, in _iterencode
    o = _default(o)
  File "C:\Python34\lib\json\encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tkinter.StringVar object at 0x02B72DF0> is not JSON serializable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 241, in _saveDataTest
    print(json.dumps(self.JSONdata, sort_keys=False, indent=1, separators=(',', ': ')))
  File "C:\Python34\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python34\lib\json\encoder.py", line 194, in encode
    chunks = list(chunks)
  File "C:\Python34\lib\json\encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 429, in _iterencode
    o = _default(o)
  File "C:\Python34\lib\json\encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tkinter.StringVar object at 0x024E8090> is not JSON serializable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 242, in _saveDataTest
    print(json.dumps(self.JSONdata, sort_keys=False, indent=1, separators=(',', ': ')))
  File "C:\Python34\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python34\lib\json\encoder.py", line 194, in encode
    chunks = list(chunks)
  File "C:\Python34\lib\json\encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 429, in _iterencode
    o = _default(o)
  File "C:\Python34\lib\json\encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tkinter.StringVar object at 0x02C49090> is not JSON serializable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 241, in _saveDataTest
    print(json.dumps(self.JSONdata, sort_keys=False, indent=1, separators=(',', ': ')))
  File "C:\Python34\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Python34\lib\json\encoder.py", line 194, in encode
    chunks = list(chunks)
  File "C:\Python34\lib\json\encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "C:\Python34\lib\json\encoder.py", line 429, in _iterencode
    o = _default(o)
  File "C:\Python34\lib\json\encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tkinter.StringVar object at 0x024C90B0> is not JSON serializable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 126, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 164, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'check', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 192, in _buildEntryTableSubEntry
    checkoptions = tk.Frame(frame, relief=tk.GROOVE, background="#FFEBEB", borderwidth=1, padding=(0,0,0,0))
  File "C:\Python34\lib\tkinter\__init__.py", line 2582, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-padding"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 45, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 121, in _BuildMainWindow
    tableData['basic']['csv'][1] = {}
IndexError: list assignment index out of range
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 198, in <lambda>
    , validate='focusout', validatecommand=lambda:self._validateCSV(ent))
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 240, in _validateCSV
    value = string(value).capwords()
TypeError: 'module' object is not callable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 111, in _BuildMainWindow
    tableData['basic']['phone'][1] = {}
IndexError: list assignment index out of range
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 111, in _BuildMainWindow
    tableData['basic']['phone'][1] = {}
IndexError: list assignment index out of range
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 124, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 160, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 178, in _buildEntryTableSubEntry
    lab = tk.Label(frame, text=item['name'], relief=tk.GROOVE, background="#FFD9D9", width=20, borderwidth=1)
TypeError: 'int' object is not subscriptable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 124, in _BuildMainWindow
    self._buildEntryTable(basicInfo, tableData['basic'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 160, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'list', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 178, in _buildEntryTableSubEntry
    lab = tk.Label(frame, text=item['name'], relief=tk.GROOVE, background="#FFD9D9", width=20, borderwidth=1)
TypeError: 'int' object is not subscriptable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 114, in _BuildMainWindow
    tableData['personal']['csv'] = [0, 1]
KeyError: 'personal'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 91, in _BuildMainWindow
    tableData['personal']['text'][2] = {}
KeyError: 'text'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 88, in _BuildMainWindow
    tableData['personal']['phone'][1] = {}
KeyError: 'phone'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 143, in _BuildMainWindow
    self._buildEntryTable(personalInfo, tableData['personal'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 181, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'csv', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 213, in _buildEntryTableSubEntry
    , validate='focusout', validatecommand=lambda:self._validateCSV(ent), height=4)
  File "C:\Python34\lib\tkinter\__init__.py", line 2514, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-height"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 143, in _BuildMainWindow
    self._buildEntryTable(personalInfo, tableData['personal'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 181, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'csv', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 213, in _buildEntryTableSubEntry
    , validate='focusout', validatecommand=lambda:self._validateCSV(ent), height=4)
  File "C:\Python34\lib\tkinter\__init__.py", line 2961, in __init__
    Widget.__init__(self, master, 'text', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-validatecommand"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 143, in _BuildMainWindow
    self._buildEntryTable(personalInfo, tableData['personal'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 181, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'csv', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 213, in _buildEntryTableSubEntry
    , validate='focusout', validatecommand=lambda:self._validateCSV(ent), height=4)
  File "C:\Python34\lib\tkinter\__init__.py", line 2514, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-height"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 143, in _BuildMainWindow
    self._buildEntryTable(personalInfo, tableData['personal'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 181, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'csv', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 213, in _buildEntryTableSubEntry
    , validate='focusout', height=4)
  File "C:\Python34\lib\tkinter\__init__.py", line 2961, in __init__
    Widget.__init__(self, master, 'text', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-textvariable"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 143, in _BuildMainWindow
    self._buildEntryTable(personalInfo, tableData['personal'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 181, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'csv', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 213, in _buildEntryTableSubEntry
    , height=4)
  File "C:\Python34\lib\tkinter\__init__.py", line 2961, in __init__
    Widget.__init__(self, master, 'text', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-textvariable"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 143, in _BuildMainWindow
    self._buildEntryTable(personalInfo, tableData['personal'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 181, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'csv', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 214, in _buildEntryTableSubEntry
    ent.insert(0, item['value'])
  File "C:\Python34\lib\tkinter\__init__.py", line 3140, in insert
    self.tk.call((self._w, 'insert', index, chars) + args)
_tkinter.TclError: bad text index "0"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 43, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 46, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 148, in _BuildMainWindow
    self._buildEntryTable(personalInfo, tableData['personal'])
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 189, in _buildEntryTable
    self._buildEntryTableSubEntry(item, 'note', frame, tableData, gridIndex)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 255, in _buildEntryTableSubEntry
    ent.grid(row=gridIndex['r'], column=gridIndex['c'], sticky=(tk.E, tk.W))
UnboundLocalError: local variable 'ent' referenced before assignment
